import pymongo

problem1_info={
    "title":"How to proccess string in c++?",
    "post_date": "2013-01-22 11:12:00",
    "content":"I want to write a program that takes an string like x^2+1 and understand it. I want to ask the user to enter her/his function and I want to be able to process and understand it. Any Ideas?",
    "tags":["C++", "string"]
}

problem2_info={
    "title":"How to remove specific strings from a list?",
    "post_date": "2013-03-02 17:12:00",
    "content":"From the following list how can I remove elements ending with Text. My expected result is a=['1,2,3,4'] My List is a=['1,2,3,4,5Text,6Text'] Should i use ends with to go about this problem? ",
    "tags":["Python"]
}

problem3_info={
    "title":"Update multiple DIV's from one JSON call",
    "post_date": "2013-12-22 11:16:00",
    "content":"I have searched a lot but as I have limited skills in javascript I have decided to ask for assistance I have created a json format output generated by an ASP page on another webserver that looks like ... ",
    "tags":["Javascript", "Jquery", "Json"]
}

def importProblems():
    problemSets.remove()
    problemSets.insert(problem1_info)
    problemSets.insert(problem2_info)
    problemSets.insert(problem3_info)

def valid():
    for problem in problemSets.find():
        print problem
        print '\n'

conn=pymongo.Connection("localhost",27017)
Web2_0FinalTestDB=conn["Web2_0FinalTestDB"]
problemSets=Web2_0FinalTestDB["problemSets"]
importProblems()
valid()

